# HTML Configuration
[[language]]
name = "html"
scope = "source.html"
injection-regex = "html"
file-types = ["html", "htm"]
language-servers = ["html-lsp", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[language-server.html-lsp]
command = "vscode-html-language-server"
args = ["--stdio"]
config = { provideFormatter = true, completion = { completeFunctionCalls = true }, validation = { styles = true, scripts = true } }

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

# CSS Configuration
[[language]]
name = "css"
scope = "source.css"
injection-regex = "css"
file-types = ["css", "scss"]
language-servers = ["css-lsp"]
formatter = { command = "prettier", args = ["--parser", "css"] }

[language-server.css-lsp]
command = "vscode-css-language-server"
args = ["--stdio"]
config = { provideFormatter = true, completion = { completeFunctionCalls = true }, validation = { validate = true } }

# Elixir Configuration
[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs"]
roots = ["mix.exs"]
auto-format = true

[language.debugger]
name = "elixir-dap"
transport = "stdio"
command = "/usr/local/bin/elixir-dap"

[[language.debugger.templates]]
name = "default"
kind = "launch"
request = "launch"
args = { program = "mix", args = ["test"] }

# Python Configuration
[[language]]
name = "python"
language-servers = ["pyright", "ruff-lsp"]
formatter = { command = "black", args = ["-", "-q"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff-lsp]
command = "ruff-lsp"
