[[language]]
name = "html"
scope = "source.html"
injection-regex = "html"
file-types = ["html", "htm"]
roots = []
language-servers = ["html-lsp", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
scope = "source.css"
injection-regex = "css"
file-types = ["css", "scss"]
roots = []
language-servers = ["css-lsp"]
formatter = { command = "prettier", args = ["--parser", "css"] }

[language-server.html-lsp]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.html-lsp.config]
provideFormatter = true
completion = { completeFunctionCalls = true }
validation = { styles = true, scripts = true }

[language-server.css-lsp]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.css-lsp.config]
provideFormatter = true
completion = { completeFunctionCalls = true }
validation = { validate = true }

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs"]
roots = ["mix.exs"]
auto-format = true

[language.debugger]
name = "elixir-dap"
transport = "stdio"
command = "/usr/local/bin/elixir-dap"

[[language.debugger.templates]]
name = "default"
kind = "launch"
request = "launch"
args = { program = "mix", args = ["test"] }
